### ISSUE TITLE
python version?

### ISSUE THREAD

**Issue by vism2889** [tidalcycles/tidal-bootstrap#10]
having trouble using the install script, mainly getting this output:

```
File "/Users/morganvisnesky/Downloads/davidgranstrom-tidal-bootstrap-55b6864/tidal-bootstrap.command", line 77
    print "Please respond with 'yes' or 'no'"
                                            ^
SyntaxError: Missing parentheses in call to 'print'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
Guessing it's because I have my machine defaulting to python3.6?
 Is there a way around this? Thanks for your time!

**Comment by davidgranstrom** [comment]
Try editing the [first line](https://github.com/tidalcycles/tidal-bootstrap/blob/55b68646293dc6b15f8eb09799c4b491218b7584/tidal-bootstrap.command#L1) of the script to point to python2. Default installation path for python (2) on macOS  should be `/usr/bin/python` or if you have installed a later version with homebrew `/usr/local/bin/python2`

Another solution is to delete that line entirely and run the script like a usual python program e.g. `python2 tidal-bootstrap.command`

**Comment by vism2889** [comment]
changing to `#!/usr/bin/env python2` seemed to do the trick.  Any reason that this shouldn't permanently be replaced, so it always points to python2?  Just curious, I actually don't know.  Second question:  How hard would it be to make a version of this that removes old or conflicting installs of tidal before installing anything new? or possibly prompts you about keeping or deleting existing tidal and SC installs?

EDIT: Also thanks a ton for your help!

**Comment by davidgranstrom** [comment]
Great! I'm not sure macOS ships `python2` by default, so I think its safest to keep it the way it is for now.

However, the script could surely be rewritten to work with both python2/3 easily. I don't actively maintain this script any more, it has been transfered to the tidal organization recently and I'm hoping the development will continue from here!

**Comment by vism2889** [comment]
So MacOS does ship python 2 by default, also this script only works with python2, at least until its updated, mainly `print` statements have `()` in python 3.  Leaving it the way it is, the script will try and use the systems default python, which many people these days have set to python3 or some intstall of anaconda, which will not work with this file.  Understand you are no longer maintaining, how should i go about proposing this change?

**Comment by davidgranstrom** [comment]
Yes. The script was intended to work "out-of-the-box" for a standard macOS install which ships with python 2.x by default.

Updating the script to work with both 2/3 or making sure it uses python2 by default would be great for sure. I think the best way is to fork this repo, make the changes, and submit a pull request and continue the discussion from there.

**Comment by vism2889** [comment]
@davidgranstrom  Cool!  Thank you for your help, I submitted a request for the python2 specifier, I think I could make this compatible with python 2 and 3 pretty easily, or at least attempt it.  Mainly I'm thinking you could put `try:` blocks around any print statements or python2 specific stuff, and have `except:` blocks with python3 alternatives.  Maybe will attempt soon if you think that could work.

**Comment by yaxu** [comment]
Thanks both, I've accepted the PR. Python3 compatibility would be great longer term!

**Comment by yaxu** [comment]
I changed this back to `python` for now, as `python2` wasn't working on one of the macs I helped install today.. I'm not sure how we can make this work in all cases..

**Comment by vism2889** [comment]
Oh snap... I'll see if I can mess with it.  I'll try getting it to work with python 2 and 3.  Sorry that fix didn't last too long, also i think that issue with ghci/haskell platform can possibly be remedied by changing the `deps` variable now listed as `'ghci'` to `'haskell-platform'`.  Dunno how to specify 8.4.1 though..

**Comment by james-see** [comment]
Since it is over a year later and still no python3 support, I wrote a simple bash script that should install everything and setup TidalCycles for you no problem. Sometimes bash is fine for these things as opposed to a full CLI. Here is the script to download and run, enjoy and I welcome feedback. @davidgranstrom @yaxu @vism2889 https://gist.github.com/jamesacampbell/0622533809b1e2e6df845d8fee6c069d

**Comment by yaxu** [comment]
Thanks @jamesacampbell! I don't have a mac so can't test it, unfortunately.

**Comment by vism2889** [comment]
Nice one @jamesacampbell!  I'll test this out when I get a chance.

**Comment by yaxu** [comment]
@jamesacampbell when you say it's untested, do you mean you have never run it?

**Comment by yaxu** [comment]
@jamesacampbell I'd be happy to take a PR if you think the shell script is an improvement, but can't test it at all myself as I am macless

**Comment by james-see** [comment]
@yaxu I am saying untested elsewhere besides my personal macbook pro. I am being super cautious because I don't want to claim that it works without some rigor in others trying it first.

**Comment by yaxu** [comment]
I've worked with the script a little bit so it should now install the complete system.
I've swapped it in, in place of the python.

**Comment by yaxu** [comment]
(Thanks a lot @jamesacampbell!)

**Comment by james-see** [comment]
Glad to see it in use. Cheers
