### ISSUE TITLE
Does homebrew still support haskell-platform?

### ISSUE THREAD

**Issue by vaibhavb** [tidalcycles/tidal-bootstrap#15]
I got following error trying to install haskell-platform on OSX 

>brew install haskell-platform
Error: No available formula with the name "haskell-platform" 
We no longer package haskell-platform. Consider installing ghc,
cabal-install and stack instead:
  brew install ghc cabal-install stack

Should the script need an update?

**Comment by yaxu** [comment]
Now rewritten to use ghcup (and not homebrew)
