### ISSUE TITLE
supercollider failure to install

### ISSUE THREAD

**Issue by heyimjohnhi** [tidalcycles/tidal-bootstrap#16]
i have no idea why but i keep getting this

![Screen Shot 2019-03-24 at 19 13 34](https://user-images.githubusercontent.com/48890917/54884444-08579180-4e69-11e9-8ecd-c89633e80189.png)

help?

**Comment by james-see** [comment]
@heyimjohnhi This script no longer works. Please try my bash script at https://gist.github.com/jamesacampbell/0622533809b1e2e6df845d8fee6c069d and let me know if it works for you. Thanks

**Comment by yaxu** [comment]
@jamesacampbell's shell script is now the default.
