### ISSUE TITLE
Script doesn't work without sudo

### ISSUE THREAD

**Issue by rahji** [tidalcycles/tidal-bootstrap#3]
Not sure if it's the way that homebrew was installed on this computer way back when, but the script doesn't work unless I run it under sudo. Here's the error I get:

fatal: could not create leading directories of '/usr/local/Library/Taps/caskroom/homebrew-cask': Permission denied
Could not setup `brew cask`, quitting.

**Comment by rahji** [comment]
Even with sudo, it fails with the following error:

Setting up brew cask.. (this could take a while)
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 257268, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 257268 (delta 21), reused 19 (delta 8), pack-reused 257224
Receiving objects: 100% (257268/257268), 78.26 MiB | 2.13 MiB/s, done.
Resolving deltas: 100% (178930/178930), done.
Checking connectivity... done.
Tapped 0 formulae
Installing: supercollider
Error: Unknown command: cask
Could not install supercollider quitting.

**Comment by rahji** [comment]
I'm assuming homebrew was installed on this machine as root. Reinstalled homebrew, removing old unwritable directories as prompted, and now the script works.

**Comment by rahji** [comment]
Hm.. I guess there are still issues. It failed when it got to SuperDirt. 

Checking if SuperDirt quark is installed..
SuperDirt quark was not found

Traceback (most recent call last):
  File "./tidal-bootstrap.command", line 283, in <module>
    main()
  File "./tidal-bootstrap.command", line 279, in main
    check_packages()
  File "./tidal-bootstrap.command", line 175, in check_packages
    + "Sorry, all packages could not be installed"
TypeError: bad operand type for unary +: 'str'

**Comment by davidgranstrom** [comment]
Hi, thank you for reporting this. I will look into it.

If its only the SuperDirt dependency that is missing, you should open the file `install-superdirt-quark.scd` in SuperCollider and follow the instructions there. This will install the SuperDirt quark.

**Comment by rahji** [comment]
Thanks David - actually more went wrong.. I'm assuming your script also does this at some point "cabal install tidal". Apparently that failed but the script didn't complain about it. Running "cabal install tidal" from a shell prompt gave errors about a ton of  prereqs failing to compile. I was able to get around the problem by reinstalling Haskell (apparently I had an old version on my computer already). After that, the command worked fine.
