### ISSUE TITLE
Move to tidalcycles org?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/tidal-bootstrap#8]
This script is great but needs a tweak, I think to install haskell core rather than haskell platform.

I'm wondering though whether it'd better to move it under the `tidalcycles` org at this point for community support there? I have a feeling we discussed this before on the tidal slack room (now a rocketchat room on http://talk.lurk.org).

**Comment by davidgranstrom** [comment]
Thanks! Yes, I believe that is the case. I haven't really had the time to keep the script up to date for a while now so I think moving it to the `tidalcycles` org would be great! 

How would you like to proceed? After reading [this article](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/), I think there are two ways to do this: 
I could transfer the repo to you, or you could add me as a collaborator to the tidalcycles org and I could transfer it once that is done. I could transfer it to you directly if that seems easier?

I will also add a deprecation notice to this repo/gh-pages once the repo's been transferred.

**Comment by yaxu** [comment]
Righto! I added you as a collaborator on the org, so you should be able to do the transfer now.

**Comment by davidgranstrom** [comment]
Thank you! I just tried to transfer the repo but I don't have write permissions in the organization.

From the github help docs:

> Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own. If Allow members to create repositories for this organization has been disabled in the receiving organization, only organization owners can transfer repositories into the organization.

Should I transfer it to you instead?

**Comment by yaxu** [comment]
Ok I set you as 'owner' of the organisation @davidgranstrom 
If that doesn't work feel free to try transferring via me
Thanks very much !

**Comment by davidgranstrom** [comment]
@yaxu Great, thanks! Looks like the repo has been transferred! Please feel free to remove my admin privileges from the org.
